### ISSUE TITLE
The settings of hyperparameters for training

### ISSUE THREAD

**Issue by SkylarShow** [zerohd4869/SACL#6]
Hello! I would like to know if I need to modify some hyperparameter values if I want to train a new model by removing the contrastive learning part. My paper is related to your project, so I would really appreciate it if you could answer this question!

**Comment by zerohd4869** [comment]
> Hello! I would like to know if I need to modify some hyperparameter values if I want to train a new model by removing the contrastive learning part. My paper is related to your project, so I would really appreciate it if you could answer this question!

If you are using the same model backbone as our SACL-LSTM, you can refer to the sh script presented in the "Quick Start" section of this repo for the hyperparameter search range. Thank you!
